### ISSUE TITLE
Dashboard view removing events that haven'

### ISSUE THREAD

**Issue by mburman440** [toymachiner62/myezteam-frontend#7]

**Comment by toymachiner62** [comment]
That haven't happened? Can you elaborate?

**Comment by mburman440** [comment]
11:00am I can't see who is coming to the 11:30 Friday Broomball.   Would like to see it.

**Comment by mburman440** [comment]
Sorry fat fingered when typing caused missing info

**Comment by toymachiner62** [comment]
@doapp-jeremy I believe this is an issue with the backend. Can you take a look? I think what we want is to return the event until the current time is greater than the end time of an event.

**Comment by mburman440** [comment]
looking into it deeper, I can see today's event on the team specific event view

**Comment by toymachiner62** [comment]
@doapp-jeremy I think the reason that the upcoming events are not being returned like an hour before the event, while the team events are showing until at least the start of the event is the difference between these 2 lines of code:

This query gets the next 3 events https://github.com/doapp-jeremy/myezteam-webservices/blob/master/src/main/java/com/myezteam/db/mysql/EventDAO.java#L71 and uses mysqls `DATEDIFF` function.

while this query gets all the events for a team https://github.com/doapp-jeremy/myezteam-webservices/blob/master/src/main/java/com/myezteam/db/mysql/EventDAO.java#L84 and uses mysqls `DATE_SUB` function.

I think if you change them both to use `DATE_SUB` it will show all events returned from both `/events` and `/teams/<team_id>/events` to return the events at least until the event start time.

Thoughts?

**Comment by doapp-jeremy** [comment]
Ok, I made that change, we'll see how it works.

**Comment by toymachiner62** [comment]
@mburman440 let us know if it behaves as expected for your next event.

**Comment by mburman440** [comment]
We can look together at next weeks practice in Kasson

**Comment by mburman440** [comment]
Friday Broomball is not there right now in the dashboard right now

**Comment by toymachiner62** [comment]
@doapp-jeremy I guess the mysql date function didn't fix it. This is still an issue and it tested and it is related to the api call.

it's 1:03 right now and I created an event for team id 207 for 1:30. 

This is what the team page uses to show events and returns data: http://ws.myezteam.com/v1/teams/207/events?api_key=9c0ba686-e06c-4a2c-821b-bae2a235fd3d
This is what the dashboard uses and does NOT return data: http://ws.myezteam.com/v1/events?api_key=9c0ba686-e06c-4a2c-821b-bae2a235fd3d

**Comment by doapp-jeremy** [comment]
Yeah, I'll have to take a look, hopefully can get to it this afternoon.

**Comment by doapp-jeremy** [comment]
Ok, I got it changed, it was filtered out on the server.  Events will now show up for an hour after their start time

**Comment by toymachiner62** [comment]
Closed via https://github.com/doapp-jeremy/myezteam-webservices/commit/89cd2207a9f1d4b85c2dc77197b73a4eb07c56bd
