### ISSUE TITLE
Delete a team that I created

### ISSUE THREAD

**Issue by rynop** [toymachiner62/myezteam-frontend#9]
I'm unable to del teams that I've created. The toggle team settings cog only shows up for the 1st team in list (even if I use the `search for team` filter).

Here is a screencast showing how to reproduce: [cantdel.mov.zip](https://github.com/toymachiner62/myezteam-frontend/files/2805512/cantdel.mov.zip)

**Comment by toymachiner62** [comment]
@rynop If i remember right, the reason you can't delete the State Farm team is b/c you're not the one that created the team. The way i think it works is that only the person that created the team can delete it.

**Comment by rynop** [comment]
Ah you are right, I thought I created other team(s) but it turns out I did not.  Closing as this is a dupe of https://github.com/toymachiner62/myezteam-frontend/issues/8
